// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	entities "github.com/aofdev/fiber-versioning-boilerplate/api/versions/v1/entities"
	mock "github.com/stretchr/testify/mock"
)

// IUserUsecase is an autogenerated mock type for the IUserUsecase type
type IUserUsecase struct {
	mock.Mock
}

// GetAllUser provides a mock function with given fields:
func (_m *IUserUsecase) GetAllUser() (*entities.User, error) {
	ret := _m.Called()

	var r0 *entities.User
	if rf, ok := ret.Get(0).(func() *entities.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
