// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	entities "github.com/aofdev/fiber-versioning-boilerplate/api/versions/v1/entities"
	mock "github.com/stretchr/testify/mock"
)

// IUserRepository is an autogenerated mock type for the IUserRepository type
type IUserRepository struct {
	mock.Mock
}

// GetAllUser provides a mock function with given fields: id
func (_m *IUserRepository) GetAllUser(id string) (*entities.User, error) {
	ret := _m.Called(id)

	var r0 *entities.User
	if rf, ok := ret.Get(0).(func(string) *entities.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
