// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	fiber "github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"

	usecases "github.com/aofdev/fiber-versioning-boilerplate/api/versions/v1/usecases"
)

// IUserRouter is an autogenerated mock type for the IUserRouter type
type IUserRouter struct {
	mock.Mock
}

// getAllUser provides a mock function with given fields: u
func (_m *IUserRouter) getAllUser(u usecases.UserUsecase) func(*fiber.Ctx) error {
	ret := _m.Called(u)

	var r0 func(*fiber.Ctx) error
	if rf, ok := ret.Get(0).(func(usecases.UserUsecase) func(*fiber.Ctx) error); ok {
		r0 = rf(u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(*fiber.Ctx) error)
		}
	}

	return r0
}
